//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagedList.Mvc.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PagedList.Mvc.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to page:.
        /// </summary>
        internal static string GoToFormRenderOptions_LabelFormat {
            get {
                return ResourceManager.GetString("GoToFormRenderOptions_LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string GoToFormRenderOptions_SubmitButtonFormat {
            get {
                return ResourceManager.GetString("GoToFormRenderOptions_SubmitButtonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing items {0} through {1} of {2}.
        /// </summary>
        internal static string ItemSliceAndTotalFormat {
            get {
                return ResourceManager.GetString("ItemSliceAndTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string PageCountAndCurrentLocationFormat {
            get {
                return ResourceManager.GetString("PageCountAndCurrentLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string TwitterBootstrapPager_LinkToNextPageFormat {
            get {
                return ResourceManager.GetString("TwitterBootstrapPager_LinkToNextPageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string TwitterBootstrapPager_LinkToPreviousPageFormat {
            get {
                return ResourceManager.GetString("TwitterBootstrapPager_LinkToPreviousPageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer &amp;rarr;.
        /// </summary>
        internal static string TwitterBootstrapPagerAligned_LinkToNextPageFormat {
            get {
                return ResourceManager.GetString("TwitterBootstrapPagerAligned_LinkToNextPageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;larr; Older.
        /// </summary>
        internal static string TwitterBootstrapPagerAligned_LinkToPreviousPageFormat {
            get {
                return ResourceManager.GetString("TwitterBootstrapPagerAligned_LinkToPreviousPageFormat", resourceCulture);
            }
        }
    }
}
